### ISSUE TITLE
TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [1] of <type 'int'>

### ISSUE THREAD

**Issue by hz1207** [FutureWater/SPHY#2]
1-1-2000  t = 1
Traceback (most recent call last):
  File "C:\python\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\python\lib\site-packages\SPHY\main.py", line 1578, in <module>
    main(sys.argv[1:])
  File "C:\python\lib\site-packages\SPHY\main.py", line 1563, in main
    RunSPHY.run()
  File "C:\Program Files\PCRaster40\python\pcraster\framework\dynamicFramework.py", line 65, in run
    self._runDynamic()
  File "C:\Program Files\PCRaster40\python\pcraster\framework\frameworkBase.py", line 362, in _runDynamic
    self._userModel().dynamic()
  File "C:\python\lib\site-packages\SPHY\main.py", line 856, in dynamic
    self.GlacTable['GLAC_T'] = self.GlacTable['MOD_T'] - (self.GlacTable['MOD_H'] - self.GlacTable['GLAC_H']) * float(self.TLapse_table.loc[self.curdate.month])
  File "C:\python\lib\site-packages\pandas\core\indexing.py", line 1500, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "C:\python\lib\site-packages\pandas\core\indexing.py", line 1912, in _getitem_axis
    self._validate_key(key, axis)
  File "C:\python\lib\site-packages\pandas\core\indexing.py", line 1799, in _validate_key
    self._convert_scalar_indexer(key, axis)
  File "C:\python\lib\site-packages\pandas\core\indexing.py", line 262, in _convert_scalar_indexer
    return ax._convert_scalar_indexer(key, kind=self.name)
  File "C:\python\lib\site-packages\pandas\core\indexes\base.py", line 2881, in _convert_scalar_indexer
    return self._invalid_indexer('label', key)
  File "C:\python\lib\site-packages\pandas\core\indexes\base.py", line 3067, in _invalid_indexer
    kind=type(key)))
TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [1] of <type 'int'>

I can't find what the problem is.

**Comment by SQPaul** [comment]
Hi hz1207, did you solve the error? 

I have the same problem.

**Comment by zhanghui2020** [comment]
> Hi hz1207, did you solve the error?
> 
> I have the same problem.
Check the consistency of the spatial extent of the input files and the vesion of python.

**Comment by bingfeiguohai** [comment]
Hello, can you use the SHPY model?
















在 2022-05-17 11:13:22，"zhanghui2020" ***@***.***> 写道：

Hi hz1207, did you solve the error?

I have the same problem.
Check the consistency of the spatial extent of the input files and the vesion of python.

**Comment by bingfeiguohai** [comment]
Hello, can you use the SHPY model?



At 2022-05-17 10:06:17, "SQPaul" ***@***.***> wrote:

Hi hz1207, did you solve the error?

I have the same problem.

**Comment by SQPaul** [comment]
> 

Hello, yes! I can use the SPHYv2.2.1.

**Comment by bingfeiguohai** [comment]
Hi, excuse me. I was wondering how you run the SPHY model. Then the parameter calibration is carried out when the SPHY model is run. Will automatic parameter calibration be performed?




May I add your contact information so that we can communicate with each other? My wechat account is bingfeiguohai--.
















在 2022-06-05 00:52:44，"Paul Sandoval Quilodrán" ***@***.***> 写道：

Hello, yes! I can use the SPHYv2.2.1.
